### ISSUE TITLE
ブラックボックステスト汎用ツール

### ISSUE THREAD

**Issue by begyyal** [begyyal/symposium#7]
IFの検討から作成迄。

**Comment by begyyal** [comment]
action.yml
```
inputs:
  definition:
    required: false
    default: 'bbdef'
  useOutput:
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
```
